### ISSUE TITLE
Snowman 2016

### ISSUE THREAD

**Issue by tfiers** [tfiers/arenberg-online#12]
Kopieer space/bal views en templates
"snowman2016"
Twee soorten tickets: volwassenen €10, kinderen (onder 12): €5
Production: Snowman 2016
Performance 1 of 2: za 14 feb (17u, 18u30)

**Comment by lennartbu** [comment]
nu mee bezig. 14 februari is een zondag, heb 13 februari genomen, en als locatie heb ik PDS gezet - dat kan nog aangepast worden

**Comment by lennartbu** [comment]
database in gitignore? nu kan ik de veranderingen die ik in database gedaan heb niet pushen?

heb backend van snowman2016 zowat geschreven, kan nog niet getest worden op site want er is nog geen frontend

**Comment by lennartbu** [comment]
is af, alle referenties naar space zijn weg (behalve in namen functies maar dat maakt niet uit), nu nog mailgun in orde en dan is dat dat
