### ISSUE TITLE
E-mails

### ISSUE THREAD

**Issue by tfiers** [tfiers/arenberg-online#14]
Niet meer via mijn gmail versturen, 
maar via Mailgun (zie arenberg-secure voor login-gegevens).

Een mail moet verstuurd worden als tickets besteld zijn (met confirmatie en betalingsgegevens).
(functie email_user (en email_admin) en email settings in settings.py moeten hiervoor aangepast worden).
- arenbergorkest.be moet nog geverifieerd worden
  Daarom moeten we aan Ulyssis vragen om DNS records voor arenbergorkest.be toe te voegen,
  hier te vinden: https://mailgun.com/app/domains/arenbergorkest.be
  We hebben DNS records voor sending and tracking nodig (dus niet voor receiving!).
- Overview sending email through mailgun: https://help.mailgun.com/hc/en-us/articles/202464990-How-do-I-start-sending-email-
- Meer info over sending, met python examples: https://documentation.mailgun.com/api-sending.html#sending
- Je kan nu al testen met emails verzenden vanaf snowman-concert.be
  (dat domein is wel al geverifieerd)

**Comment by lennartbu** [comment]
auto update and create mailing lists, mailing works (basic version)
